# Source - https://stackoverflow.com/a/73229032
# Posted by aknosis
# Retrieved 2026-08-11, License - CC BY-SA 4.0

version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
